name: "🛠️ VPP Build Test Merge"
description: |
  This GitHub Action <...>.

inputs:
  is_build:
    description: 'Run only build phase (no tests, no merge)'
    required: false
    default: false
    type: boolean
  is_verify:
    description: 'Run build + test phases (skip merge)'
    required: false
    default: false
    type: boolean
  is_merge:
    description: 'Run build + merge phases (skip tests)'
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Determine phase selection (Build/Test/Merge)
      shell: bash
      run: |
        BUILD_INPUT='${{ inputs.is_build || github.event.inputs.is_build }}'
        TEST_INPUT='${{ inputs.is_verify || github.event.inputs.is_verify }}'
        MERGE_INPUT='${{ inputs.is_merge || github.event.inputs.is_merge }}'
        RUN_TEST_PHASE=true
        RUN_MERGE_PHASE=true
        # Precedence: Build > Test > Merge (if multiple true)
        if [[ "$BUILD_INPUT" == 'true' ]]; then
          RUN_TEST_PHASE=false
          RUN_MERGE_PHASE=false
          PHASE_MODE='BUILD'
        elif [[ "$TEST_INPUT" == 'true' ]]; then
          RUN_TEST_PHASE=true
          RUN_MERGE_PHASE=false
          PHASE_MODE='TEST'
        elif [[ "$MERGE_INPUT" == 'true' ]]; then
          RUN_TEST_PHASE=false
          RUN_MERGE_PHASE=true
          PHASE_MODE='MERGE'
        else
          PHASE_MODE='FULL'
        fi
        echo "RUN_TEST_PHASE=${RUN_TEST_PHASE}" >> $GITHUB_ENV
        echo "RUN_MERGE_PHASE=${RUN_MERGE_PHASE}" >> $GITHUB_ENV
        echo "PHASE_MODE=${PHASE_MODE}" >> $GITHUB_ENV
        echo "Selected phase mode: ${PHASE_MODE} (RUN_TEST_PHASE=${RUN_TEST_PHASE} RUN_MERGE_PHASE=${RUN_MERGE_PHASE})"

    - name: Setup Environment
      uses: pmikus/.github/.github/actions/setup_executor_env@main

    - name: Setup Docker Environment
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/scripts/setup_vpp_ubuntu_docker_test.sh

    - name: Install VPP external dependencies
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/scripts/setup_vpp_ext_deps.sh

    - name: Build VPP
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/scripts/build.sh