name: "🛠️ VPP Build Test Merge"
description: |
  This GitHub Action <...>.

inputs:
  is_build:
    description: 'Run only build phase (no tests, no merge)'
    required: false
    default: false
    type: boolean
  is_verify:
    description: 'Run build + test phases (skip merge)'
    required: false
    default: false
    type: boolean
  is_merge:
    description: 'Run build + merge phases (skip tests)'
    required: false
    default: false
    type: boolean

runs:
  steps:
    - name: Determine phase selection (Build/Test/Merge)
      shell: bash
      run: |
        BUILD_INPUT='${{ inputs.is_build || github.event.inputs.is_build }}'
        TEST_INPUT='${{ inputs.is_verify || github.event.inputs.is_verify }}'
        MERGE_INPUT='${{ inputs.is_merge || github.event.inputs.is_merge }}'
        RUN_TEST_PHASE=true
        RUN_MERGE_PHASE=true
        # Precedence: Build > Test > Merge (if multiple true)
        if [[ "$BUILD_INPUT" == 'true' ]]; then
          RUN_TEST_PHASE=false
          RUN_MERGE_PHASE=false
          PHASE_MODE='BUILD'
        elif [[ "$TEST_INPUT" == 'true' ]]; then
          RUN_TEST_PHASE=true
          RUN_MERGE_PHASE=false
          PHASE_MODE='TEST'
        elif [[ "$MERGE_INPUT" == 'true' ]]; then
          RUN_TEST_PHASE=false
          RUN_MERGE_PHASE=true
          PHASE_MODE='MERGE'
        else
          PHASE_MODE='FULL'
        fi
        echo "RUN_TEST_PHASE=${RUN_TEST_PHASE}" >> $GITHUB_ENV
        echo "RUN_MERGE_PHASE=${RUN_MERGE_PHASE}" >> $GITHUB_ENV
        echo "PHASE_MODE=${PHASE_MODE}" >> $GITHUB_ENV
        echo "Selected phase mode: ${PHASE_MODE} (RUN_TEST_PHASE=${RUN_TEST_PHASE} RUN_MERGE_PHASE=${RUN_MERGE_PHASE})"

    - name: Setup Environment
      uses: pmikus/.github/.github/actions/setup_executor_env@main

    - name: Setup Docker Environment
      shell: bash
      run: |
        #OS_ID=$(grep '^ID=' /etc/os-release | cut -f2- -d= | sed -e 's/\"//g')
        #OS_VERSION_ID=$(grep '^VERSION_ID=' /etc/os-release | cut -f2- -d= | sed -e 's/\"//g')

        if [ -n ${DOCKER_TEST} ] ; then
          # for 4 cores:
          # framework.VppTestCase.MIN_REQ_SHM + (num_cores * framework.VppTestCase.SHM_PER_PROCESS)
          # 1073741824 == 1024M (1073741824 >> 20)
          MEM=1024M
          if [[ ${MAKE_PARALLEL_JOBS} == '16' ]]
          then
              # arm build are running with 16 cores, empirical evidence shows
              # that 2048M is enough
              MEM=2048M
          fi
          sudo mount -o remount /dev/shm -o size=${MEM} || true
                echo "/dev/shm remounted with size='${MEM}'"
        fi

    - name: Install VPP external dependencies
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/scripts/setup_vpp_ext_deps.sh

    - name: Build VPP
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/scripts/build.sh