---
name: "🛠️ Test VPP image using 'make test'"
description: |
  This GitHub Action tests the VPP image built using the vpp-build action.

inputs:
  TEST_JOBS:
    description: "Number of parallel jobs for 'make test'"
    required: false
    default: "16"
    type: string
  TEST_RETRIES:
    description: "Number of retries for flaky tests"
    required: false
    default: "3"
    type: string
  MAKE_TEST_OS:
    description: "OS to run 'make test' on"
    required: false
    default: "ubuntu-24.04"
    type: string
  MAKE_TEST_MULTIWORKER_OS:
    description: "OS to run 'make test' with multiworker config"
    required: false
    default: "debian-12"
    type: string
  VPPAPIGEN_TEST_OS:
    description: "OS to run 'vppapigen' tests on"
    required: false
    default: "ubuntu-24.04"
    type: string
  VPP_WORKER_COUNT:
    description: "Number of VPP workers to use for multiworker tests"
    required: false
    default: "2"
    type: string
  TUI_LINE:
    description: "Delimiter line for TUI output"
    required: false
    default: "*******************************************************************"
    type: string

runs:
  using: "composite"
  steps:
    - name: VPP Make Test
      shell: bash
      env:
        TEST_JOBS: ${{ inputs.TEST_JOBS }}
        TEST_RETRIES: ${{ inputs.TEST_RETRIES }}
        MAKE_TEST_OS: ${{ inputs.MAKE_TEST_OS }}
        MAKE_TEST_MULTIWORKER_OS: ${{ inputs.MAKE_TEST_MULTIWORKER_OS }}
        VPPAPIGEN_TEST_OS: ${{ inputs.VPPAPIGEN_TEST_OS }}
        VPP_WORKER_COUNT: ${{ inputs.VPP_WORKER_COUNT }}
        TUI_LINE: ${{ inputs.TUI_LINE }}
      run: |
          set -euxo pipefail

          BUILD_RESULT="SUCCESSFULLY COMPLETED"
          BUILD_ERROR=""
          RETVAL="0"

          make_test() {
              if ! make UNATTENDED=yes test-dep ; then
                  BUILD_ERROR="FAILED 'make test-dep'"
                  return
              fi
              if grep -q "${OS_ID}-${OS_VERSION_ID}" <<< "${VPPAPIGEN_TEST_OS}"; then
                  if ! src/tools/vppapigen/test_vppapigen.py ; then
                      BUILD_ERROR="FAILED src/tools/vppapigen/test_vppapigen.py"
                      return
                  fi
              fi
              if grep -q "${OS_ID}-${OS_VERSION_ID}" <<< "${MAKE_TEST_OS}"; then
                  if ! make COMPRESS_FAILED_TEST_LOGS=yes TEST_JOBS="$TEST_JOBS" RETRIES=3 test ; then
                      BUILD_ERROR="FAILED 'make test'"
                      return
                  fi
              else
                  echo "Skip running 'make test' on ${OS_ID}-${OS_VERSION_ID}"
              fi
              if grep -q "${OS_ID}-${OS_VERSION_ID}" <<< "${MAKE_TEST_MULTIWORKER_OS}"; then
                  if ! make VPP_WORKER_COUNT="${VPP_WORKER_COUNT}" COMPRESS_FAILED_TEST_LOGS=yes \
                          TEST_RETRIES="${TEST_RETRIES}" TEST_JOBS="${TEST_JOBS}" test ; then
                      BUILD_ERROR="FAILED 'make VPP_WORKER_COUNT=${VPP_WORKER_COUNT} COMPRESS_FAILED_TEST_LOGS=yes \
                          RETRIES=${TEST_RETRIES} TEST_JOBS=${TEST_JOBS} test'"
                      return
                  else
                      echo -e "\n* VPP ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^}" \
                              "MULTIWORKER MAKE TEST SUCCESSFULLY COMPLETED\n"
                  fi
              else
                  echo "Skip running MULTIWORKER MAKE TEST on ${OS_ID}-${OS_VERSION_ID}"
              fi
          }

          echo "$TUI_LINE"
          make_test
          if [ -n "$BUILD_ERROR" ] ; then
              BUILD_RESULT="$BUILD_ERROR"
              RETVAL="1"
          fi
          echo -e "\n$TUI_LINE\n* VPP ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^}" \
                  "BUILD $BUILD_RESULT\n$TUI_LINE\n"
          exit $RETVAL
