---
name: "🛠️ VPP Install Optional Dependencies"
description: |
  This GitHub Action installs the necessary optional dependencies for VPP.

inputs:
  TUI_LINE:
    description: "Delimiter line for TUI output"
    required: false
    default: "*******************************************************************"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Optional Dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "${{ inputs.TUI_LINE }}"
        echo "Installing VPP optional dependencies..."
        make UNATTENDED=yes install-opt-deps
        echo "${{ inputs.TUI_LINE }}"