---
name: "🛠️ Test VPP image using 'make test'"
description: |
  This GitHub Action tests the VPP image built using the vpp-build action. This action requires
  the vpp-install-deps and vpp-install-ext-deps actions to have been run previously to install
  all necessary dependencies for running the tests.

inputs:
  BUILD_TYPE:
    description: "Type of build: debug or release"
    required: false
    default: "debug"
    type: string
  HS_TEST_DIR:
    description: "Directory containing HostStack Test (HST) framework tests"
    required: false
    default: "${WORKSPACE}/test-c/hs-test"
    type: string
  TUI_LINE:
    description: "Delimiter line for TUI output"
    required: false
    default: "*******************************************************************"
    type: string

runs:
  using: "composite"
  steps:
    - name: VPP Make Test
      shell: bash
      env:
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
        HS_TEST_DIR: ${{ inputs.HS_TEST_DIR }}
        TUI_LINE: ${{ inputs.TUI_LINE }}
      run: |
          set -euxo pipefail

          BUILD_RESULT="SUCCESSFULLY COMPLETED"
          BUILD_ERROR=""
          RETVAL="0"

          hst_debug_build_run() {
              if ! make VERBOSE=true VPPSRC="${WORKSPACE}" -C "$HS_TEST_DIR" build-debug ; then
                  BUILD_ERROR="FAILED 'make -C $HS_TEST_DIR build-debug'"
                  return
              fi
              if ! make VERBOSE=true VPPSRC="${WORKSPACE}" -C "$HS_TEST_DIR" test-debug ; then
                  BUILD_ERROR="FAILED 'make -C $HS_TEST_DIR test-debug'"
                  return
              fi
          }

          hst_build_run() {
              if ! make VERBOSE=true VPPSRC="${WORKSPACE}" -C "$HS_TEST_DIR" build ; then
                  BUILD_ERROR="FAILED 'make -C $HS_TEST_DIR build'"
                  return
              fi
              if ! make VERBOSE=true VPPSRC="${WORKSPACE}" -C "$HS_TEST_DIR" test ; then
                  BUILD_ERROR="FAILED 'make -C $HS_TEST_DIR test'"
                  return
              fi
          }

          echo "$TUI_LINE"
          echo "Check for system core files"
          ls -la /scratch/nomad || true # DEBUG ONLY, DO NOT COMMIT
          ls -la /scratch/ccache || true # DEBUG ONLY, DO NOT COMMIT
          ls -l /var/crash || true

          if [ "${{ inputs.BUILD_TYPE }}" == "debug" ] ; then
              hst_debug_build_run
          else
              hst_build_run
          fi

          echo "Check for system core files"
          ls -l /var/crash || true

          if [ -n "$BUILD_ERROR" ] ; then
              BUILD_RESULT="$BUILD_ERROR"
              RETVAL="1"
          fi
          echo -e "\n$TUI_LINE\n* VPP ${BUILD_TYPE^^} ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^}" \
                  "HST $BUILD_RESULT\n$TUI_LINE\n"
          exit $RETVAL
