---
name: "🛠️ Build VPP image"
description: |
  This GitHub Action builds the VPP Docker image.

inputs:
  MAKE_PARALLEL_JOBS:
    description: "Number of parallel jobs for 'make' (overrides MAKE_PARALLEL_JOBS)"
    required: false
    default: ""
    type: string
  BUILD_TYPE:
    description: "Type of build: debug or release"
    required: false
    default: "release"
    type: string
  TUI_LINE:
    description: "Delimiter line for TUI output"
    required: false
    default: "*******************************************************************"
    type: string

runs:
  using: "composite"
  steps:
    - name: Build VPP
      shell: bash
      env:
        MAKE_PARALLEL_JOBS: ${{ inputs.MAKE_PARALLEL_JOBS }}
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
        TUI_LINE: ${{ inputs.TUI_LINE }}
      run: |
        set -euo pipefail

        BUILD_RESULT="SUCCESSFULLY COMPLETED"
        BUILD_ERROR=""
        RETVAL="0"

        build_vpp() {
            echo "Building VPP. Number of cores for build set with" \
                  "MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS}."
            if [ -f extras/scripts/build_static_vppctl.sh ]; then
                if ! extras/scripts/build_static_vppctl.sh ; then
                    BUILD_ERROR="FAILED 'extras/scripts/build_static_vppctl.sh'"
                    return
                fi
            fi
            if [ "$BUILD_TYPE" == "debug" ] ; then
                if ! make UNATTENDED=yes MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS} build ; then
                    BUILD_ERROR="FAILED 'make UNATTENDED=yes MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS} build'"
                    return
                fi
            else
              if ! make UNATTENDED=yes MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS} pkg-verify ; then
                  BUILD_ERROR="FAILED 'make UNATTENDED=yes MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS} pkg-verify'"
                  return
              fi
            fi
        }

        echo "$TUI_LINE"
        build_vpp
        if [ -n "${BUILD_ERROR}" ] ; then
            BUILD_RESULT="${BUILD_ERROR}"
            RETVAL="1"
        fi
        echo -e "\n$TUI_LINE\n* VPP ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^}" \
                "BUILD $BUILD_RESULT\n$TUI_LINE\n"
        exit $RETVAL