name: vpp-verify

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  build-test:
    name: Build & Test VPP
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/vpp-build-test-merge.yml

