name: vpp-merge

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

jobs:
  merge-vpp:
    name: Build & Test VPP
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204', 'debian12']
        branch: [master, stable/2502, stable/2506]
        executor_arch: ['x86_64', 'aarch64']
        build_type: ${{ (inputs.build_type == 'debug' || github.event.inputs.build_type == 'debug') && fromJson('["debug"]') || (inputs.build_type == 'release' || github.event.inputs.build_type == 'release') && fromJson('["release"]') || fromJson('["debug", "release"]') }}
        exclude:
          # Exclude debian12 on aarch64 for all builds
          - os: 'debian12'
            executor_arch: 'aarch64'

          # Debug build exclusions - only keep [master, ubuntu2204, x86_64]
          # Exclude non-master branches for debug builds
          - build_type: 'debug'
            branch: 'stable/2502'
          - build_type: 'debug'
            branch: 'stable/2506'

          # Exclude non-ubuntu2204 OS for debug builds
          - build_type: 'debug'
            os: 'ubuntu2404'
          - build_type: 'debug'
            os: 'debian12'

          # Exclude aarch64 architecture for debug builds
          - build_type: 'debug'
            executor_arch: 'aarch64'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      # Ensures uniqueness per run
      CACHE_DATE: ${{ github.run_id }}
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      DOCKER_TEST: 1
      EXECUTOR_ARCH: ${{ matrix.executor_arch }}
      GERRIT_BRANCH: ${{ matrix.branch }}
      JOB_NAME: ${{ github.job }}-${{ matrix.branch == 'master' && 'master' || matrix.branch == 'stable/2502' && '2502' || '2506' }}-${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: 16
      MAKE_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || matrix.os == 'ubuntu2404' && 'ubuntu-24.04' || 'debian-12' }}
      MAKE_TEST_MULTIWORKER_OS: 'debian-12'
      SHM_SIZE: ${{ matrix.executor_arch == 'aarch64' && '4096M' || '2048M' }}
      STREAM: ${{ matrix.branch == 'master' && 'master' || matrix.branch == 'stable/2502' && '2502' || '2506' }}
      TEST_RETRIES: 3
      VPPAPIGEN_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || matrix.os == 'ubuntu2404' && 'ubuntu-24.04' || 'debian-12' }}
      VPP_SRC_DIR: /scratch/docker-build/vpp
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Build & Merge VPP
        uses: pmikus/vpp/.github/actions/vpp_build_test_merge@master
        with:
          is_merge: true