name: vpp-verify

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  get-workflow-data:
    name: Get Workflow Data
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.read-outputs.outputs.branch }}
      refspec: ${{ steps.read-outputs.outputs.refspec }}
      url: ${{ steps.read-outputs.outputs.url }}
    steps:
      - name: Download Workflow Artifacts via GitHub API
        id: download-artifact
        run: |
          set -euxo pipefail
          # Get the artifact download URL
          ARTIFACTS_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts"

          echo "Fetching artifacts from: $ARTIFACTS_URL"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"

          # Get all artifacts info for debugging
          ARTIFACTS_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$ARTIFACTS_URL")

          echo "=== All artifacts in this workflow run ==="
          echo "$ARTIFACTS_RESPONSE" | jq -r '.artifacts[] | "\(.name) (ID: \(.id), expired: \(.expired))"' || echo "No artifacts or jq error"

          # Find the workflow-outputs artifact
          ARTIFACT_ID=$(echo "$ARTIFACTS_RESPONSE" | jq -r '.artifacts[] | select(.name=="workflow-outputs") | .id')

          if [ "$ARTIFACT_ID" = "null" ] || [ -z "$ARTIFACT_ID" ]; then
            echo "Error: workflow-outputs artifact not found"
            echo "Available artifacts:"
            echo "$ARTIFACTS_RESPONSE" | jq -r '.artifacts[].name' || echo "Failed to parse artifacts"

            # Try to find any workflow-outputs-* artifacts as fallback
            MATRIX_ARTIFACT_ID=$(echo "$ARTIFACTS_RESPONSE" | jq -r '.artifacts[] | select(.name | startswith("workflow-outputs-")) | .id' | head -1)
            if [ -n "$MATRIX_ARTIFACT_ID" ] && [ "$MATRIX_ARTIFACT_ID" != "null" ]; then
              echo "Found matrix artifact instead, using: $MATRIX_ARTIFACT_ID"
              ARTIFACT_ID="$MATRIX_ARTIFACT_ID"
            else
              echo "No suitable artifacts found"
              exit 1
            fi
          fi

          echo "Using artifact ID: $ARTIFACT_ID"

          # Download the artifact
          DOWNLOAD_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip"
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$DOWNLOAD_URL" -o artifact.zip

          # Extract the artifact
          unzip -q artifact.zip
          echo "=== Extracted contents ==="
          ls -la

      - name: Read Outputs
        id: read-outputs
        run: |
          set -euxo pipefail
          # Check if files are in workflow-outputs subdirectory first
          if [ -f "workflow-outputs/branch" ]; then
            echo "Found files in workflow-outputs directory"
            BRANCH_FILE="workflow-outputs/branch"
            REFSPEC_FILE="workflow-outputs/refspec"
            URL_FILE="workflow-outputs/url"
          elif [ -f "branch" ]; then
            echo "Found files in root directory"
            BRANCH_FILE="branch"
            REFSPEC_FILE="refspec"
            URL_FILE="url"
          else
            echo "Error: workflow output files not found in expected locations"
            echo "Current directory contents:"
            ls -la
            if [ -d "workflow-outputs" ]; then
              echo "workflow-outputs directory contents:"
              ls -la workflow-outputs/
            fi
            exit 1
          fi

          # Validate files exist and are readable
          if [ ! -f "$BRANCH_FILE" ] || [ ! -f "$REFSPEC_FILE" ] || [ ! -f "$URL_FILE" ]; then
            echo "Error: One or more required files are missing"
            echo "Expected: $BRANCH_FILE, $REFSPEC_FILE, $URL_FILE"
            exit 1
          fi

          # Read the content and set outputs
          BRANCH_VALUE=$(cat "$BRANCH_FILE" | tr -d '\n' | tr -d '\r')
          REFSPEC_VALUE=$(cat "$REFSPEC_FILE" | tr -d '\n' | tr -d '\r')
          URL_VALUE=$(cat "$URL_FILE" | tr -d '\n' | tr -d '\r')

          {
              echo "branch=$BRANCH_VALUE"
              echo "refspec=$REFSPEC_VALUE"
              echo "url=$URL_VALUE"
          } >> $GITHUB_OUTPUT

          echo "Successfully read outputs:"
          echo "  branch=$BRANCH_VALUE"
          echo "  refspec=$REFSPEC_VALUE"
          echo "  url=$URL_VALUE"

  verify-build-test:
    name: Build & Test VPP
    needs: get-workflow-data
    uses: ./.github/workflows/vpp-build-test-merge.yml
    with:
      branch: ${{ needs.get-workflow-data.outputs.branch }}
      refspec: ${{ needs.get-workflow-data.outputs.refspec }}
      url: ${{ needs.get-workflow-data.outputs.url }}
    secrets: inherit
