name: vpp-verify

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

permissions:
  contents: read

jobs:
  verify-build-test:
    name: Build & Test VPP
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/vpp-build-test-merge.yml
    with:
      is_merge: false
    secrets: inherit
