name: vpp-merge

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  merge-build-test:
    name: Merge,Build & Test VPP
    # FIXME: merge job should run on gerrit change merge event
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/vpp-build-test-merge.yml
    with:
      is-merge: true

