name: vpp-verify

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types: [completed]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to verify (master, stable/2502, stable/2506)"
        required: true
        default: "master"
        type: choice
        options:
          - master
          - stable/2502
          - stable/2506
      commit_sha:
        description: "Exact commit SHA to verify (optional)"
        required: false
        type: string
      reason:
        description: "Reason for manual verification"
        required: false
        default: "Manual VPP Build/Test Verification Run"
        type: string
      builder_type:
        description: "Builder image type (prod or sandbox)"
        required: false
        default: "prod"
        type: choice
        options:
          - prod
          - sandbox
      build_type:
        description: "Build type selection (debug, release, or both)"
        required: false
        default: "both"
        type: choice
        options:
          - both
          - debug
          - release
      make_parallel_jobs:
        description: "MAKE_PARALLEL_JOBS value (number of parallel make jobs)"
        required: false
        default: "16"
        type: string

jobs:
  verify-build-test:
    name: Build & Test VPP
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204', 'debian12']
        branch: [master, stable/2502, stable/2506]
        executor_arch: ['x86_64', 'aarch64']
        build_type: ${{ (inputs.build_type == 'debug' || github.event.inputs.build_type == 'debug') && fromJson('["debug"]') || (inputs.build_type == 'release' || github.event.inputs.build_type == 'release') && fromJson('["release"]') || fromJson('["debug", "release"]') }}
        exclude:
          # Exclude debian12 on aarch64 for all builds
          - os: 'debian12'
            executor_arch: 'aarch64'

          # Debug build exclusions - only keep [master, ubuntu2204, x86_64]
          # Exclude non-master branches for debug builds
          - build_type: 'debug'
            branch: 'stable/2502'
          - build_type: 'debug'
            branch: 'stable/2506'

          # Exclude non-ubuntu2204 OS for debug builds
          - build_type: 'debug'
            os: 'ubuntu2404'
          - build_type: 'debug'
            os: 'debian12'

          # Exclude aarch64 architecture for debug builds
          - build_type: 'debug'
            executor_arch: 'aarch64'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      # Ensures uniqueness per run
      CACHE_DATE: ${{ github.run_id }}
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      DOCKER_TEST: 1
      EXECUTOR_ARCH: ${{ matrix.executor_arch }}
      GERRIT_BRANCH: ${{ matrix.branch }}
      JOB_NAME: ${{ github.job }}-${{ matrix.branch == 'master' && 'master' || matrix.branch == 'stable/2502' && '2502' || '2506' }}-${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: ${{ inputs.make_parallel_jobs || github.event.inputs.make_parallel_jobs || '16' }}
      MAKE_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || matrix.os == 'ubuntu2404' && 'ubuntu-24.04' || 'debian-12' }}
      MAKE_TEST_MULTIWORKER_OS: 'debian-12'
      SHM_SIZE: ${{ matrix.executor_arch == 'aarch64' && '4096M' || '2048M' }}
      STREAM: ${{ matrix.branch == 'master' && 'master' || matrix.branch == 'stable/2502' && '2502' || '2506' }}
      TEST_RETRIES: 3
      VPPAPIGEN_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || matrix.os == 'ubuntu2404' && 'ubuntu-24.04' || 'debian-12' }}
      VPP_SRC_DIR: /scratch/docker-build/vpp
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Gerrit Checkout
        # yamllint disable-line rule:line-length
        uses: lfit/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63 # v0.9
        with:
          gerrit-refspec: ${{ github.event.inputs.GERRIT_REFSPEC }}
          gerrit-project: ${{ github.event.inputs.GERRIT_PROJECT }}
          gerrit-url: ${{ vars.GERRIT_URL }}
          delay: "30s"
          ref: refs/heads/${{ github.event.inputs.GERRIT_BRANCH }}

      - name: VPP Build Test Merge
        uses: pmikus/vpp/.github/actions/vpp_build_test_merge@master
        with:
          branch: ${{ github.event.workflow_run.head_branch || github.event.inputs.branch }}
          commit_sha: ${{ github.event.workflow_run.head_sha || github.event.inputs.commit_sha }}
          reason: ${{ github.event_name == 'workflow_run' && format('Verify after checkstyle run ID {0}', github.event.workflow_run.id) || github.event.inputs.reason }}
          builder_type: ${{ github.event.inputs.builder_type || 'prod' }}
          build_type: ${{ github.event.inputs.build_type || 'both' }}
          make_parallel_jobs: ${{ github.event.inputs.make_parallel_jobs || '16' }}
          is_verify: true
