name: vpp-verify

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

jobs:
  merge-vpp:
    name: Build & Merge VPP
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./vpp-build-test-merge.yml
    with:
      is_merge: false
    secrets: inherit
