name: vpp-merge

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  merge-build-test:
    name: Merge,Build & Test VPP
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/vpp-build-test-merge.yml
    with:
      is-merge: true
      gerrit-branch: ${{ vars.GERRIT_BRANCH }}
      gerrit-refspec: ${{ vars.GERRIT_REFSPEC }}
      gerrit-url: ${{ vars.GERRIT_URL }}
    secrets: inherit